apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: qw4opll1w-nodejs 
  description: Secure Supply Chain Example for Node.js+Express REST API with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures, attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment.   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used tssc-gitops as the grouping
    argocd/app-selector: tssc/gitops=qw4opll1w-nodejs
    backstage.io/kubernetes-id: qw4opll1w-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: qw4opll1w-nodejs
    quay.io/repository-slug: rhtap_qe/rhtap-qe-nodejs
  tags: ["nodejs", "express", "ubi8", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 